### ISSUE TITLE
Can not proceed the script under the condition of "server returned 404 Not Found"

### ISSUE THREAD

**Issue by curelesss** [HikariKnight/quickpassthrough#26] opened 2024-04-02 09:05 UTC
not sure, if the following might be considered as an issue, and thank you for taking your time of reading this.

`sudo ./quickpassthrough`

Terminal returns:

```
Download failed: server returned 404 Not Found
2024/04/02 16:32:22 If the above error is 404, then we could not communicate with the GitHub API
 Please manually download and extract ls-iommu to: utils/
You can download it from: https://github.com/HikariKnight/ls-iommu/releases
```

Thus, I followed the instruction, and downloaded the `ls-iommu_Linux_x86_64.tar.gz` file from the corresponding project release page and extract the `ls-iommu` to the directory `quickpassthrough/utils/`

and, rerun the command

`sudo ./quickpassthrough`

Terminal returns:

```
Download failed: server returned 404 Not Found
Existing ls-iommu binary detected in "utils/", will use that instead as the GitHub API did not respond.
2024/04/02 16:33:15 open utils/ls-iommu_Linux_x86_64.tar.gz: no such file or directory

```
then, I copied the `ls-iommu_Linux_x86_64.tar.gz` file to the `utils` directory, and rerun the same command.

the following is the Terminal output:

```
Download failed: server returned 404 Not Found
Existing ls-iommu binary detected in "utils/", will use that instead as the GitHub API did not respond.
2024/04/02 16:46:43 Failed to open: utils/ls-iommu_Linux_x86_64.tar.gz
2024/04/02 16:46:43 open utils/ls-iommu_Linux_x86_64.tar.gz: no such file or directory

```
and the file `ls-iommu_Linux_x86_64.tar.gz` I coped to `utils` directory was deleted automatically.

the problem seems to be recursive.

**Comment by HikariKnight** [comment] 2024-04-02 09:21
new urls caused by switching `ls-iommu` to github actions. will fix this when i get home from work

**Comment by HikariKnight** [comment] 2024-04-02 09:29
actually @curelesss i had some time during my lunch break, fixing this now, thank you!

**Comment by HikariKnight** [comment] 2024-04-02 09:33
fixed with https://github.com/HikariKnight/quickpassthrough/commit/a9b889e5acf57feac1330ef6d964811073d2ecca
[once this finishes](https://github.com/HikariKnight/quickpassthrough/actions/runs/8520571250/job/23336966467)

there will be a new release on the release page with the fix :)

**Closed by HikariKnight** 2024-04-02 09:33 UTC

**Comment by curelesss** [comment] 2024-04-02 11:00
thank you for your quick response and help, great project.
